name: Porting Request
description: Request that an existing app be ported
title: '[PORT]'
labels:
  - 'port'
body:
  - type: markdown
    attributes:
      value: |
        Please read the conditions below carefully before submitting your idea.
        
        * Apps related to intellectual property infringement are not allowed.
        * We can't guarantee that anyone will work on porting suggested apps.
        * We encourage you to port the app yourself. This would be a great contribution to the webOS homebrew community.
  - type: checkboxes
    attributes:
      label: 'Conditions for submitting an app idea'
      options:
        - label: 'I have read and agree to the conditions above'
          required: true
        - label: 'I would like to port this app myself'
          required: false
  - type: textarea
    attributes:
      label: 'Describe the app to port'
      placeholder: 'Please provide a detailed description of the app you would like to see ported'