name: Repo Related
description: Submit bug reports or feedback regarding the repository itself
title: '[REPO]'
labels:
  - 'repo'
body:
  - type: markdown
    attributes:
      value: |
        This template intended for issues regarding the repo itself and the formats/schemas it uses, for example:

        * Issues encountered while using this code to host your own repo
        * Suggestions to add new fields to the package schema
  - type: textarea
    attributes:
      label: 'Description'
      placeholder: 'Please provide a detailed description of the issue or feedback'