name: Site Related
description: Submit bug reports or feedback regarding the repo.webosbrew.org site
title: '[SITE]'
labels:
  - 'site'
body:
  - type: textarea
    attributes:
      label: 'Description'
      placeholder: 'Please provide a detailed description of the issue or feedback'